Update ask script

diff --git a/ask b/ask
--- a/ask
+++ b/ask
@@ -1,14 +1,49 @@
 #/bin/bash
 
-ASK_APP_BUILD_PATH=$PWD'/ask-app/build'
-ASK_REMOTE_MODULE_BUILD_PATH=$PWD'/ask-remote-module/build'
+# Print path
+# echo "pwd: `pwd`"
+# echo "\$0: $0"
+# echo "basename: `basename "$0"`"
+# echo "dirname: `dirname "$0"`"
 
-if [[ ! -d $ASK_REMOTE_MODULE_BUILD_PATH ]]; then
-  ./gradlew :ask-remote-module:build &>/dev/null
+APP_HOME=`dirname "$0"`
+REMOTE_MODULE_BUILD_PATH=$APP_HOME/ask-remote-module/build
+APP_BUILD_PATH=$APP_HOME/ask-app/build
+
+cd "$APP_HOME" >/dev/null
+
+echo $APP_HOME
+
+if [[ ! -d $REMOTE_MODULE_BUILD_PATH ]]; then
+  ./gradlew :ask-remote-module:build >/dev/null
 fi
 
-if [[ ! -d $ASK_APP_BUILD_PATH ]]; then
-  ./gradlew :ask-app:build &>/dev/null
+if [[ ! -d $APP_BUILD_PATH ]]; then
+  ./gradlew :ask-app:build >/dev/null
 fi
 
-java -cp '.:'$PWD'/ask-app/build/libs/ask-app.jar:'$PWD'/ask-app/libs/gson-2.7.jar' com.androidstarterkit.Ask $@
+# Determine the Java command to use to start the JVM.
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+        JAVACMD="$JAVA_HOME/bin/java"
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
+else
+    JAVACMD="java"
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+fi
+
+CLASSPATH=$APP_HOME/ask-app/build/libs/ask-app.jar:$APP_HOME/ask-app/libs/gson-2.7.jar
+
+exec "$JAVACMD" -cp "$CLASSPATH" com.androidstarterkit.Ask "$@"
